version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./storage/app/public:/var/www/public/storage
    ports:
      - "8080:80"
    depends_on:
      - php
    container_name: ${PROJECT_NAME}-nginx

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 9012:9000
    container_name: ${PROJECT_NAME}-php
    depends_on:
      - db

  # db:
  #   image: postgres:14
  #   restart: always
  #   environment:
  #       POSTGRES_DB: ${DB_DATABASE}
  #       POSTGRES_USER: ${DB_USERNAME}
  #       POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./docker/postgres/datadir:/var/lib/postgresql/data
  #   container_name: ${PROJECT_NAME}-postgres
  #   networks:
  #     - laravel

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        # MYSQL_USER: ${DB_USERNAME}
        # MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: ${PROJECT_NAME}-mysql

volumes:
    db_data:
